import './globals.css';
import { Inter } from 'next/font/google';
import { Toaster } from '@/components/ui/toaster';
import Provider from '@/components/provider/Provider';
import { ThemeProvider } from '@/components/provider/theme-provider';
import Navbar from '@/components/navigation/Navbar';
import MainPageMenu from '@/components/Menu';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="dark:bg-neutral-900/80 bg-neutral-100/40 min-h-screen">
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          <Provider>
            <Navbar />

            <div className="mt-14 container max-w-7xl m-0 p-0 sm:mx-auto h-full">
              <div className="max-w-7xl md:grid grid-cols-[1fr_240px] flex flex-col gap-4 sm:px-4 sm:pt-4">
                {children}
                <MainPageMenu />
              </div>
            </div>
          </Provider>
        </ThemeProvider>
        <Toaster />
      </body>
    </html>
  );
}
